# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d8c8cb54f69f86e01d36b1bb316d36e7d9649fca3c9b7ac161f1fa40c5959e93025f0d7f76a8a1788f4d19728379d50384cbb91e88636828bcec8ce20022e7a

test:
  secret_key_base: 72a6036379ab0de626ffb7a1331fba6a715ff3feb1b4333e01d2f29c86d65e9178a9cacbdfbc4645209df13e5c5c1fe385cb78aff16773795efffb2595625643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
